### ISSUE TITLE
Design doc: Efficient APIs in preparation for React migration

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#815]
Our existing APIs result in form objects behaving like [God objects](https://en.wikipedia.org/wiki/God_object) that force the frontend to update it in its entirety, even though a user may only be creating or updating a single form field on the admin panel. This makes the application

1. Inefficient, as each small update has to replace the entire form object
2. It will also constrain the architecture, performance, and correctness of any future React application.

The strategy to resolve this problem is multi-pronged:

1. To deprecate existing server APIs by incrementally migrating functionality out of God-like `adminform` APIs. This will help enforce the correctness of future React applications while making updates much more efficient, since only a portion of each form needs to be updated.

2. Progressively reduce our reliance on AngularJS services, by deprecating existing AngularJS services and moving them out of the AngularJS framework. The new services should be written in TypeScript and treated like an SDK, and can be conveniently reused in [custom React hooks](https://reactjs.org/docs/hooks-custom.html), or [queries](https://react-query.tanstack.com/docs/guides/queries) and [mutations](https://react-query.tanstack.com/docs/guides/mutations) with `react-query`.

Undertaking this work also means that we won’t have to feature freeze as early, since a significant part of the React migration can be performed while we’re still on AngularJS

## Current server APIs
_To be deprecated_
- `GET /:formId/adminform`
- `PUT /:formId/adminform`
- `DELETE /:formId/adminform`

## New server APIs

Settings tab
- [ ] `GET /api/admin/forms/:formId/settings` \*
- [x] `PATCH /api/admin/forms/:formId/settings` \* (#1383)
(prioritise this as it is a blocker for webhook retries)

Dashboard view
- [ ] `GET /api/admin/forms` List all forms
- [ ] `POST /api/admin/forms` Create form
- [ ] `DELETE /api/admin/forms/:formId` delete form by id
- [ ] `POST /api/admin/forms/:formId/duplicate` duplicate form by id

Build tab
- [ ] `GET /api/admin/forms/:formId/build` retrieve form data relevant to building a form
- [ ] `PUT /api/admin/forms/:formId/fields/:fieldId` update field (#1481)
- [ ] `PUT /api/admin/forms/:formId/fields/:fieldId/reorder` reorder field (#1482)
- [ ] `POST /api/admin/forms/:formId/fields/:fieldId/duplicate` duplicate field (#1483)
- [ ] `POST /api/admin/forms/:formId/fields` create field (#1484)
- [ ] `DELETE /api/admin/forms/:formId/fields/:fieldId` delete field (#1485)
- [ ] `GET /api/admin/forms/:formId/fields/:fieldId` retrieve single field 
- [ ] `PATCH /api/admin/forms/:formId/start-page` update start page of form (#1486)
- [ ] `PATCH /api/admin/forms/:formId/end-page` update end page of form (#1487)

Logic tab
- [ ] `GET /api/admin/forms/:formId/logic` retrieve form data relevant to modifying form logic
- [ ] `POST /api/admin/forms/:formId/logic` create logic (#1489)
- [ ] `PUT /api/admin/forms/:formId/logic/:logicId` update logic (#1488)
- [ ] `DELETE /api/admin/forms/:formId/logic/:logicId` delete logic (#1490)

Collaborators
- [ ] `GET /api/admin/forms/:formId/collaborators` retrieve form collaborators
- [ ] `PATCH /api/admin/forms/:formId/collaborators` add/update/delete collaborators (#1491)

**Comment by karrui** [comment]
WIP
Missing some endpoints:

- [ ] `POST /api/admin/form/:formId/start`
- [ ] `POST /api/admin/form/:formId/end`

**Comment by mantariksh** [comment]
## Frontend services without AngularJS dependencies

These services do not have any AngularJS-dependent functionality, and hence can be safely migrated to TypeScript before we move to React.
- [ ] attachments.client.service.js
- [ ] betas.client.factory.js (@mantariksh)
- [ ] color-themes.client.service.js
- [ ] form-feedback.client.factory.js
- [ ] form-fields.client.service.js (@mantariksh)
- [ ] rating.client.service.js (@mantariksh)
- [ ] spcp-redirect.client.factory.js, spcp-validate-esrvcid.client.factory.js (should be combined into 1 service)
- [ ] analytics.client.service.js
- [ ] features.client.factory.js (@mantariksh)
- [ ] admin-console.client.service.js

**Comment by karrui** [comment]
> * color-themes.client.service.js

Don't think we actually need to migrate this too haha

**Comment by mantariksh** [comment]
> Don't think we actually need to migrate this too haha

Yeah a few of these are tiny (e.g. for color themes, just delete the service and use the enum), but imo should still do to minimise surface area for React migration

**Comment by karrui** [comment]
WIP endpoints for /adminform

![image](https://user-images.githubusercontent.com/22133008/111974445-5f68cd80-8b3a-11eb-96cc-6e7bafbba3c0.png)

**Comment by liangyuanruo** [comment]
Closing in favour of creating bite-sized issues
